run:
  skip-files-use-default: true
  issues-exit-code: 0

linters-settings:
  govet:
    enabled: true
  staticcheck:
    enabled: true
  deadcode:
    enabled: true
  gofmt:
    enabled: true
  gofumpt:
    enabled: true
  goimports:
    enabled: true
  ineffassign:
    enabled: true
  errcheck:
    enabled: true
  unconvert:
    enabled: true
  varcheck:
    enabled: true
  maligned:
    enabled: true
  gocyclo:
    enabled: true
