apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: server
spec:
  type: NodePort
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
