apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: jaafarn/server:tag # Replace with your Go server image
          ports:
            - containerPort: 8090
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: SERVER_PORT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['kubectl.kubernetes.io/last-applied-configuration']
            - name: DB_HOST
              value: "postgres-service" # Use the service name to connect to Postgres
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_NAME
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_NAME
            - name: POSTGRES_SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_SSL_MODE
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: SERVER_HOST
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: SERVER_PORT