apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres
spec:
  replicas: 1 # starts the deployment controller
  selector:
    matchLabels:
      app: postgres
  template: # Starting the pod
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_PORT
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_NAME
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_NAME
            - name: POSTGRES_SSL_MODE
              valueFrom:
                configMapKeyRef:
                  name: library-config
                  key: POSTGRES_SSL_MODE
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
